### [인증] 사용자가 보유중인 메달들을 조회한다
GET {{host_api}}/api/v2/user/medals
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### [인증] 사용자의 장착중인 메달을 수정한다
PUT {{host_api}}/api/v2/user/medal
Content-Type: application/json
Authorization: {{AUTHORIZATION}}

{
    "medalType": "BUNGEOPPANG_CHALLENGER"
}

> {%
client.test("200", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
