### 테스트를 위한 세션
GET {{host_api}}/test-token

> {%
client.global.set("AUTHORIZATION", response.body["data"]["sessionId"])
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### [인증] 카카오 회원탈퇴를 요청합니다
DELETE {{host_api}}/api/v2/signout?socialType=KAKAO
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### [인증] 애플 회원탈퇴를 요청합니다
DELETE {{host_api}}/api/v2/signout?socialType=APPLE
Authorization: {{AUTHORIZATION}}

> {%
client.test("404 NOT_FOUND", function() {
    client.assert(response.status === 404, "응답 실패");
});
%}


### [인증] 로그아웃
POST {{host_api}}/api/v2/logout
Content-Type: application/json
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
