coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags:
          - unit
        paths:
          - "src"
        if_ci_failed: success
        informational: true
        only_pulls: false
    patch: false
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
