### 테스트를 위한 세션
GET {{host_api}}/test-token

> {%
client.global.set("AUTHORIZATION", response.body["data"]["token"])
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### [인증] 나의 회원 정보를 조회합니다.
GET {{host_api}}/api/v2/user/me
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### [인증] 나의 회원 정보를 수정합니다.
PUT {{host_api}}/api/v2/user/me
Content-Type: application/json
Authorization: {{AUTHORIZATION}}

{
    "name": "will"
}

> {%
client.test("200 OK or 409 Conflict", function() {
    client.assert(response.status === 200 || 409, "응답 실패");
});
%}


### 닉네임 중복 여부를 체크 요청합니다.
GET {{host_api}}/api/v2/user/name/check?name=will

> {%
client.test("200 OK or 409 Conflict", function() {
     client.assert(response.status === 409 || 200, "응답 실패");
});
%}
