### 모든 FAQ를 조회합니다.
GET {{host_api}}/api/v2/faqs

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 카테고리의 FAQ를 조회합니다.
GET {{host_api}}/api/v2/faqs?category=STORE

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 모든 FAQ 카테고리를 조회합니다.
GET {{host_api}}/api/v2/faq/categories

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
